name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        submodules: recursive  # Cloner les sous-modules
        fetch-depth: 0  # Prendre tout l'historique (optionnel)

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Backend
      uses: docker/build-push-action@v5
      with:
        context: ./studentmanagement-clone
        file: ./studentmanagement-clone/Dockerfile
        push: true
        tags: kaloina/cicd-backend:latest

    - name: Build and push Frontend
      uses: docker/build-push-action@v5
      with:
        context: ./projet-tp01-clone
        file: ./projet-tp01-clone/Dockerfile
        push: true
        tags: kaloina/cicd-frontend:latest
