name: Sync Submodules

on:
  schedule:
    - cron: '* * * * *'  
  workflow_dispatch:        # déclenchable manuellement
    inputs:
      environment:
        description: 'Environnement à déployer'
        required: true
        default: 'staging'
jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout fullstack-cicd with submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.GH_TOKEN }}  # un token avec accès en écriture

    - name: Configure Git
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    # - name: Pull latest submodules
    #   run: |
    #     git submodule update --remote --merge

    - name: Pull submodule updates
      run: |
        git submodule update --remote


    - name: Commit if there are changes
      run: |
        if ! git diff --quiet; then
          git add .
          git commit -m "Update submodules to latest commit"
          git push origin main
        else
          echo "No changes to commit"
        fi
